all: t ls cp touch cat
cat: cat.c
	gcc -o cat cat.c
touch: touch.c
	gcc -o touch touch.c
cp: cp.c
	gcc -o cp cp.c
ls: ls.c
	gcc -o ls ls.c
t: thelshel.c
	gcc -o t thelshel.c
echo: echo.c
	gcc -o echo echo.c
rm: rm.c
	gcc -o rm rm.c
clean:
	rm ls t cp touch cat echo rm
