/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg;

/**
 *
 * @author thwilliams
 */
public class GUI extends javax.swing.JFrame {
    public String filename="Needs to be set";
    Inventory a=new Inventory();
    public int worksheet_num, num_of_sheets;
    public char mathorreading;
    public String level;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Get = new javax.swing.JButton();
        Store = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        PrintAll = new javax.swing.JButton();
        PrintWholeLevel = new javax.swing.JButton();
        LessThan = new javax.swing.JButton();
        Inputfile = new javax.swing.JTextField();
        numless = new javax.swing.JTextField();
        MorR = new javax.swing.JTextField();
        Level = new javax.swing.JTextField();
        Worksheet = new javax.swing.JTextField();
        Num = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Output = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Get.setText("Get single entry");
        Get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetActionPerformed(evt);
            }
        });

        Store.setText("Enter single entry");
        Store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoreActionPerformed(evt);
            }
        });

        Add.setText("Add worksheets to entry");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Remove.setText("Take worksheets out/Subtract");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        PrintAll.setText("Get all levels for subject");
        PrintAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintAllActionPerformed(evt);
            }
        });

        PrintWholeLevel.setText("Print one level");
        PrintWholeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintWholeLevelActionPerformed(evt);
            }
        });

        LessThan.setText("Print all less than this number");

        Inputfile.setText("C://Users//tdw46//OneDrive//Desktop//worksheets.csv");

        jLabel1.setText("File(make sure this is correct)");

        jLabel2.setText("Print all less than this number: ");

        jLabel3.setText("(M)ath or (R)eading single letter");

        jLabel4.setText("Level (i.e. 3A, J)");

        jLabel5.setText("Worksheet level (i.e. 11, 131)");

        jLabel6.setText("How many worksheets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Inputfile, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Level, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(MorR, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Worksheet)
                                    .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Get, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Store, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Add, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Remove, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PrintAll, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PrintWholeLevel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Output, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numless, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LessThan)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Get)
                            .addComponent(Inputfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Store)
                            .addComponent(MorR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Add)
                            .addComponent(Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Remove)
                            .addComponent(jLabel5)
                            .addComponent(Worksheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrintAll)
                            .addComponent(jLabel6)))
                    .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrintWholeLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LessThan)
                    .addComponent(numless, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        this.filename=Inputfile.getText();
        a.loadfile(filename);
        this.level=Level.getText();
        this.mathorreading=MorR.getText().charAt(0);
        this.worksheet_num=Integer.parseInt(Worksheet.getText());
        this.num_of_sheets=Integer.parseInt(Num.getText());
        this.filename=Inputfile.getText();
        if(a.manageInputEntry4args(this.mathorreading, this.level, this.worksheet_num, this.num_of_sheets)){
                 Output.setText(a.removeCount(this.level, this.num_of_sheets, this.worksheet_num, this.mathorreading)+a.savefile(this.filename));
        }else{
                Output.setText("Error: Double-check text boxes to make sure they match\nMake sure you enter\n Whether the worksheet is math or reading\n The number of sheets \n The level to get them from\nThe worksheet number(i.e. 131)");
        }
    }//GEN-LAST:event_RemoveActionPerformed

    private void StoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoreActionPerformed
        // TODO add your handling code here:
        this.filename=Inputfile.getText();
        a.loadfile(filename);
        this.level=Level.getText();
        this.mathorreading=MorR.getText().charAt(0);
        this.worksheet_num=Integer.parseInt(Worksheet.getText());
        this.num_of_sheets=Integer.parseInt(Num.getText());
        this.filename=Inputfile.getText();
        if(a.manageInputEntry4args(this.mathorreading, this.level, this.worksheet_num, this.num_of_sheets)){
                 Output.setText(a.setCount(this.level, this.num_of_sheets, this.worksheet_num, this.mathorreading)+a.savefile(this.filename));
        }else{
                Output.setText("Error: Double-check text boxes to make sure they match\nMake sure you enter\n Whether the worksheet is math or reading\n The number of sheets \n The level to get them from\nThe worksheet number(i.e. 131)");
        }
    }//GEN-LAST:event_StoreActionPerformed

    private void GetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetActionPerformed
        // TODO add your handling code here:
         this.filename=Inputfile.getText();
        a.loadfile(filename);
        this.level=Level.getText();
        this.mathorreading=MorR.getText().charAt(0);
        this.worksheet_num=Integer.parseInt(Worksheet.getText());
        if(a.manageInput3args(this.mathorreading, this.level ,this.worksheet_num)){
                Output.setText(a.loadfile(this.filename)+"The number of worksheets is "+Integer.toString(a.getCount(this.level, this.worksheet_num,this.mathorreading)));
        }else{
            Output.setText(a.loadfile(this.filename)+"Error: Make sure you enter\n Whether the worksheet is math or reading\n The number of sheets \n The level to get them from");
        }  
    }//GEN-LAST:event_GetActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        this.filename=Inputfile.getText();
        a.loadfile(filename);
        this.level=Level.getText();
        this.mathorreading=MorR.getText().charAt(0);
        this.worksheet_num=Integer.parseInt(Worksheet.getText());
        this.num_of_sheets=Integer.parseInt(Num.getText());
        this.filename=Inputfile.getText();
        if(a.manageInputEntry4args(this.mathorreading, this.level, this.worksheet_num, this.num_of_sheets)){
                 Output.setText(a.addCount(this.level, this.num_of_sheets, this.worksheet_num, this.mathorreading)+a.savefile(this.filename));
        }else{
                Output.setText("Error: Double-check text boxes to make sure they match\nMake sure you enter\n Whether the worksheet is math or reading\n The number of sheets \n The level to get them from\nThe worksheet number(i.e. 131)");
        }
    }//GEN-LAST:event_AddActionPerformed

    private void PrintAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintAllActionPerformed
        // TODO add your handling code here:
        this.mathorreading=MorR.getText().charAt(0);
        Output.setText(a.loadfile(this.filename)+a.getAllSubjectLevels(this.mathorreading));
    }//GEN-LAST:event_PrintAllActionPerformed

    private void PrintWholeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintWholeLevelActionPerformed
        // TODO add your handling code here:
        this.filename=Inputfile.getText();
        this.level=Level.getText();
        this.mathorreading=MorR.getText().charAt(0);
        Output.setText(a.loadfile(filename)+a.getFullLevel(this.level, this.mathorreading));
    }//GEN-LAST:event_PrintWholeLevelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Get;
    private javax.swing.JTextField Inputfile;
    private javax.swing.JButton LessThan;
    private javax.swing.JTextField Level;
    private javax.swing.JTextField MorR;
    private javax.swing.JTextField Num;
    private java.awt.TextArea Output;
    private javax.swing.JButton PrintAll;
    private javax.swing.JButton PrintWholeLevel;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Store;
    private javax.swing.JTextField Worksheet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField numless;
    // End of variables declaration//GEN-END:variables
}
